"""Initial migration

Revision ID: 69d920510c1b
Revises: 
Create Date: 2025-01-31 15:51:36.963821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d920510c1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificado_enviado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.drop_column('certificado_enviado')

    # ### end Alembic commands ###
